### ISSUE TITLE
Standard secrets practice instead of .secrets.json file

### ISSUE THREAD

**Issue by 0xjjpa** [validitylabs/hopr#2]
As done properly in the `.gitignore` file, `.secrets.json` is ignored in order to avoid having people committing secrets into version control. However, `.secrets.json` isn't really much of a standard, and most applications use a `.env` file sitting in the root directory of the project.

My suggestion is to replace `.secrets.json` for an `.env` file and use [dotenv](https://medium.com/@thejasonfile/using-dotenv-package-to-create-environment-variables-33da4ac4ea8f) for setting up the environment variables, making the project fit a bit more common conventions.

Happy to implement this if agreed on doing so.

**Comment by robertkiel** [comment]
Thank you very much! Will integrate it asap

**Comment by 0xjjpa** [comment]
👋 @robertkiel only saw this now, but since I already was a bit midway, ended up making #7 , hopefully it can helps, otherwise feel free to close it and continue on your current work ☺️

**Comment by 0xjjpa** [comment]
This is no longer an issue due to the merge of #7 , thanks!
